/**
 * 
 */

var fs = require('fs');
var parseString = require('xml2js').parseString;

var parseVersionFromPomXml = function() {
    var version;
    var pomXml = fs.readFileSync('pom.xml', "utf8");
    parseString(pomXml, function (err, result){
        version = result.project.version[0];
    });
    return version;
};

module.exports = function(grunt) {

  // Project configuration.
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    uglify: {
      options: {
        banner: '/*! <%= pkg.name %> <%= grunt.template.today("yyyy-mm-dd") %> */\n'
      },
      build: {
        src: 'src/main/webapp/scripts/<%= pkg.name %>.js',
        dest: 'build/<%= pkg.name %>.min.js'
      }
    },
    
    copy: {
	  assets: {
		  expand: true, 
		  src: [
            'node_modules/angular/angular.min.js', 
            'node_modules/angular/angular.min.js.map',
            'node_modules/bootstrap/dist/css/bootstrap.min.css', 
            'node_modules/bootstrap/dist/css/bootstrap.css.map',
            'node_modules/bootstrap/dist/fonts/*', 
            'node_modules/bootstrap/dist/js/bootstrap.min.js',
            'node_modules/angular-route/angular-route.min.js', 
            'node_modules/angular-route/angular-route.min.js.map',
            'node_modules/jquery/dist/jquery.min.js', 
            'node_modules/jquery/dist/jquery.min.map',
            'node_modules/angular-translate/dist/angular-translate.min.js',
            'node_modules/angular-local-storage/dist/angular-local-storage.min.js',
            'node_modules/angular-dynamic-locale/tmhDynamicLocale.min.js', 
            'node_modules/angular-dynamic-locale/tmhDynamicLocale.min.js.map',
            'node_modules/angular-resource/angular-resource.min.js', 
            'node_modules/angular-resource/angular-resource.min.js.map',
            'node_modules/angular-ui-router/release/angular-ui-router.min.js',
            'node_modules/angular-cookies/angular-cookies.min.js', 
            'node_modules/angular-cookies/angular-cookies.min.js.map',
            'node_modules/angular-cache-buster/angular-cache-buster.js',
            'node_modules/angular-translate/dist/angular-translate-storage-cookie/angular-translate-storage-cookie.min.js',
            'node_modules/angular-translate/dist/angular-translate-loader-partial/angular-translate-loader-partial.min.js',
            'node_modules/angular-i18n/*',
            'bower_components/angular-ui-grid/ui-grid.css',
            'bower_components/angular-ui-grid/ui-grid.svg',
            'bower_components/angular-ui-grid/ui-grid.ttf',
            'bower_components/angular-ui-grid/ui-grid.woff',
            'bower_components/angular-ui-grid/ui-grid.js',
            'node_modules/bootbox/bootbox.min.js'
            ], 
          dest: 'src/main/webapp/', 
		  filter: 'isFile'
		  
	  },
    },
    ngconstant: {
        options: {
            name: 'angularSpringApp',
            deps: false,
            wrap: '"use strict";\n// DO NOT EDIT THIS FILE, EDIT THE GRUNT TASK NGCONSTANT SETTINGS INSTEAD WHICH GENERATES THIS FILE\n{%= __ngModule %}'
        },
        dev: {
            options: {
                dest: 'src/main/webapp/scripts/app/app.constants.js',
            },
            constants: {
                ENV: 'dev',
                VERSION: parseVersionFromPomXml()
            }
        },
        prod: {
            options: {
                dest: '.tmp/scripts/app/app.constants.js',
            },
            constants: {
                ENV: 'prod',
                VERSION: parseVersionFromPomXml()
            }
        }
    }
    
  });

  grunt.loadNpmTasks('grunt-contrib-concat');  
  grunt.loadNpmTasks('grunt-contrib-copy');
  grunt.loadNpmTasks('grunt-ng-constant');

  // Default task(s).
  grunt.registerTask('make-all', ['copy:assets']);

};
